# Generated by Django 4.2.7 on 2025-09-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollutedarea",
            name="polygon_coordinates",
            field=models.TextField(
                blank=True, help_text="Polygon coordinates as JSON", null=True
            ),
        ),
    ]
